name: arquitetura


services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.app.yml
  #   container_name: "app"
  #   networks:
  #     - arquitetura

  postgres:
    image: postgres:17-bookworm
    restart: always
    shm_size: 128mb
    container_name: postgres
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-postgres}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
    networks:
      - data_lake_net
    expose:
      - 5433
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      # - ./scripts/arquitura.sh:/docker-entrypoint-initdb.d/1_arquitetura.sh

  pgadmin:
    image: elestio/pgadmin:REL-9_4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL:-admin@mail.com}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD:-admin}"
      PGADMIN_LISTEN_PORT: 8080
    networks:
      - data_lake_net
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - pgadmin4:/pgadmin4/servers.json
   

  minio:
    build:
      context: .
      dockerfile: Dockerfile.minio.yml
    container_name: minio
    restart: always
    networks:
      - data_lake_net
    expose:
      - 9000
      - 9001
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER:-root}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD:-p4ssw0rd}"
    volumes:
      - miniodata:/data

  miniobucket:
    image: minio/mc
    container_name: minio_mc
    networks:
      - data_lake_net
    environment:
      MINIO_HOST: "${MINIO_HOST}"
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
    entrypoint: >
      /bin/sh -c "
      sleep 15;
      /usr/bin/mc alias set myminio ${MINIO_HOST} ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      /usr/bin/mc rm -r --force myminio/lakehouse;
      /usr/bin/mc mb myminio/lakehouse;
      /usr/bin/mc policy download myminio/lakehouse;
      /usr/bin/mc cp --recursive /tmp/data/ myminio/lakehouse;
      exit 0;
      "
    depends_on:
      - minio
    volumes:
      - ./minio:/tmp/data

volumes:
  postgres:
  pgadmin4:
  miniodata:

networks:
  data_lake_net: