FROM python:3.12-slim-bookworm


RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive && \
    pip install jupyterlab

RUN useradd -m -s /bin/basha jupyter_user

USER jupyter_user

WORKDIR /workdir/app

ENTRYPOINT ["bash", "-c", "jupyter lab --port-retries=0 --ip 0.0.0.0 --port 8888 --allow-root --IdentityProvider.token='' --ServerApp.password=''"]