FROM debian:bookworm-slim

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    curl \
    wget 

RUN mkdir /data && \
    wget https://dl.min.io/server/minio/release/linux-amd64/minio && \
    chmod +x minio

# EXPOSE 9000 9001

CMD ["bash" , "-c", "./minio server /data --console-address ':9001'"]
